export const types  = {
FETCH_ALL_BREWERIES: 'FETCH_ALL_BREWERIES',
FILTER_BREWIERIES_BY_NAME: 'FILTER_BREWIERIES_BY_NAME',
SEARCH_BREWERIES_BY_NAME: 'SEARCH_BREWERIES_BY_NAME',
SEARCH_BREWERIES_BY_NAME_SUCCESS: 'SEARCH_BREWERIES_BY_NAME_SUCCESS'
}
 
